version: '3.2'
services:
  app:
    image: yiisoftware/yii2-php:7.1-apache
    container_name: yii2-app
    ports:
      - 80:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      # Mount apache log dir
      - ./docker/app/var/log:/var/log
    environment:
      - YII_DEBUG=true
      - YII_ENV=dev
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    container_name: yii2-mysql
    volumes:
      - ./docker/mysql/etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yii2db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: yii2-phpmyadmin
    ports:
      - 8080:80
    links:
      - mysql:mysql
    environment:
      PMA_HOST: mysql
    volumes:
      - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
        - mysql

  redis:
    image: redis:3.2
    container_name: yii2-redis
